server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/prueba_tecnica_ada
    username: root
    password: 
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: false  